In [3]:
pip install seaborn

Collecting seaborn
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Requirement already satisfied: pandas>=0.25 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from seaborn) (1.5.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from seaborn) (1.23.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from seaborn) (3.6.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (22.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.1.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages\pytz-2022.6-py3.9.egg (from pandas>=0.25->seaborn) (2022.6)
Requirement already satisfied: six>=1.5 in c:\users\vincent kipruto\anaconda3\envs\gis-enviro\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.12.2
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
import seaborn as sns

In [5]:
data0=pd.read_csv("C:/Users/VINCENT KIPRUTO/Documents/Final Year ProjectðŸ˜Ž/Data/wfp_food_prices_kenya.csv")

# Data Cleaning

In [3]:
data=data0[data0['priceflag']=='actual']
data

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,KG,actual,Wholesale,KES,16.13,0.2235
2,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize (white),90 KG,actual,Wholesale,KES,1480,20.5041
3,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,KG,actual,Wholesale,KES,33.63,0.4659
4,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans (dry),90 KG,actual,Wholesale,KES,3246,44.9705
5,1/15/2006,Eastern,Kitui,Kitui,-1.366667,38.016667,cereals and tubers,Maize (white),KG,actual,Retail,KES,17,0.2355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,10/15/2022,Rift Valley,West Pokot,Makutano (West Pokot),1.253093,35.076653,pulses and nuts,Beans (rosecoco),90 KG,actual,Wholesale,KES,9432,79.3939
9976,10/15/2022,Rift Valley,West Pokot,Makutano (West Pokot),1.253093,35.076653,vegetables and fruits,Cabbage,126 KG,actual,Wholesale,KES,2007.18,16.8955
9977,10/15/2022,Rift Valley,West Pokot,Makutano (West Pokot),1.253093,35.076653,vegetables and fruits,Kale,50 KG,actual,Wholesale,KES,1385,11.6582
9978,10/15/2022,Rift Valley,West Pokot,Makutano (West Pokot),1.253093,35.076653,vegetables and fruits,Onions (dry),13 KG,actual,Wholesale,KES,643.5,5.4167
9979,10/15/2022,Rift Valley,West Pokot,Makutano (West Pokot),1.253093,35.076653,vegetables and fruits,Tomatoes,64 KG,actual,Wholesale,KES,2640,22.2222

In [4]:
data.shape

(9979, 14)

In [5]:
data.isnull().sum()

date         0
admin1       0
admin2       0
market       0
latitude     0
longitude    0
category     0
commodity    0
unit         0
priceflag    0
pricetype    0
currency     0
price        0
usdprice     0
dtype: int64

In [26]:
data.duplicated().sum()

0

In [23]:
data.head()

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,KG,actual,Wholesale,KES,16.13,0.2235
2,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize (white),90 KG,actual,Wholesale,KES,1480,20.5041
3,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans,KG,actual,Wholesale,KES,33.63,0.4659
4,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,pulses and nuts,Beans (dry),90 KG,actual,Wholesale,KES,3246,44.9705
5,1/15/2006,Eastern,Kitui,Kitui,-1.366667,38.016667,cereals and tubers,Maize (white),KG,actual,Retail,KES,17,0.2355

In [24]:
maize=data[data['commodity']=='Maize']
maize

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,KG,actual,Wholesale,KES,16.13,0.2235
11,1/15/2006,Nairobi,Nairobi,Nairobi,-1.283333,36.816667,cereals and tubers,Maize,KG,actual,Wholesale,KES,15.48,0.2145
20,1/15/2006,Nyanza,Kisumu,Kisumu,-0.1,34.75,cereals and tubers,Maize,KG,actual,Wholesale,KES,14.84,0.2055
27,1/15/2006,Rift Valley,Uasin Gishu,Eldoret town (Uasin Gishu),0.516667,35.283333,cereals and tubers,Maize,KG,actual,Wholesale,KES,12.96,0.1796
31,2/15/2006,Coast,Mombasa,Mombasa,-4.05,39.666667,cereals and tubers,Maize,KG,actual,Wholesale,KES,16.41,0.2299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9014,3/15/2022,Nairobi,Nairobi,Nairobi,-1.283333,36.816667,cereals and tubers,Maize,KG,actual,Wholesale,KES,25.03,0.221
9051,3/15/2022,Rift Valley,Nakuru,Nakuru,-0.28296,36.0744,cereals and tubers,Maize,KG,actual,Wholesale,KES,35.31,0.3118
9064,3/15/2022,Rift Valley,Uasin Gishu,Eldoret town (Uasin Gishu),0.516667,35.283333,cereals and tubers,Maize,KG,actual,Wholesale,KES,33.43,0.2952
9160,4/15/2022,Rift Valley,Nakuru,Nakuru,-0.28296,36.0744,cereals and tubers,Maize,KG,actual,Wholesale,KES,35.88,0.3112
9171,4/15/2022,Rift Valley,Uasin Gishu,Eldoret town (Uasin Gishu),0.516667,35.283333,cereals and tubers,Maize,KG,actual,Wholesale,KES,37.88,0.3285

## Converting csv to shp